### PR TITLE
create Global switch for preserveDelete

### PR DESCRIPTION
**Pull request by nkaputnik**

### CODE REVIEW

**Comment by nkaputnik** [comment]
Hallo @Sv7enNowitzki 
can you describe, where the code is that does the insert of the "Deleted" entry in this PR?
Also, how would the entry look like, so that I can update the readme file?

otherwise, this looks coprehensive, especially the test coverage...

**Comment by Sv7enNowitzki** [comment]
> Hallo @Sv7enNowitzki can you describe, where the code is that does the insert of the "Deleted" entry in this PR? Also, how would the entry look like, so that I can update the readme file?
> 
> otherwise, this looks coprehensive, especially the test coverage...

**Comment by Sv7enNowitzki** [comment]
> Hallo @Sv7enNowitzki can you describe, where the code is that does the insert of the "Deleted" entry in this PR? Also, how would the entry look like, so that I can update the readme file?
> 
> otherwise, this looks coprehensive, especially the test coverage...

Hi @nkaputnik ,

I should have provided a description in the PR, apologies for any confusion caused...

In this PR, the modifications specifically targeted towards the global switch functionality are reflected only in **_change-log.js_**. The behavior is as follows:

1. When the user sets **preserveDeletes** to **true**, it signifies that all changelogs are retained when the root entity is deleted. Also, all changelogs for the delete operation are created and inserted into the change-tracking DB table.
2. When **preserveDeletes** is set to **false** or not configured, all associated changelogs are deleted alongside the deletion of the root entity. This is our default behavior currently.

The code modifications made in **_entity-helper.js_** are for the purpose that the generated changelog count is correct, aligns with our expectations when deleting the root entity. However, there was skewness in the **ObjectID** retrieval behaviors, and the code amendments in this file are directed towards fixing this bug.

Of course, if committing in this way is impractical, I can split and submit this as two separate PRs. Indeed, that seems more rational.

Best Regards,
Wenjun

**Comment by nkaputnik** [comment]
No, that's good, I'll merge this PR and update readme and release notes...

**Pull request merged**
