### PR TITLE
Add limitations about CAP Feature toggles to the documentation / readme

### PR DESCRIPTION
**Pull request by FrankVisuals**
As discussed in [issue 116](https://github.com/cap-js/change-tracking/issues/116).

I think it's worth to add this to the readme, as it cost us quite some time to find this.

### CODE REVIEW

**Comment by FrankVisuals** [comment]
@Sv7enNowitzki (random ping because I saw you merged last) any feedback on this?

**Comment by nkaputnik** [comment]
Hello Frank,
I will be modifying your PR before we merge it.
In essence, we have annotation flags to disable the automatic addition of the change view onto the model, as well as the facet, so the solution is actually even simpler than what you propose.

It will just take a couple of days because of my other, regular workload.

Best,
Nick
________________________________

**Comment by FrankVisuals** [comment]
Thanks for the reply.  Actually, I think my proposal is part of the solution that you describe. When disabling the UI facet creation + the creation of the association you have to create the association yourself (even though then you can name it "changes").

**Comment by nkaputnik** [comment]
Exactly, then you can name it changes.

Best,
Nick

From: Frank Hufnagel ***@***.***>
Date: Friday, 27. September 2024 at 10:36
To: cap-js/change-tracking ***@***.***>
Cc: Josipovic, Nikica ***@***.***>, Comment ***@***.***>
Subject: Re: [cap-js/change-tracking] Add limitations about CAP Feature toggles to the documentation / readme (PR #120)

Thanks for the reply. Actually, I think my proposal is part of the solution that you describe. When disabling the UI facet creation + the creation of the association you have to create the association yourself (even though then you can name it "changes").

**Review by nkaputnik — APPROVED** [review]

**Pull request merged**
